### PR TITLE
Bump MSRV to 1.46

### PR DESCRIPTION
**Pull request by taiki-e**
This is because the latest bitflags (dependency of nix that is dependency of ctrlc) requires Rust 1.46.

```
error[E0658]: `if` is not allowed in a `const fn`
  --> /Users/taiki/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.22.0/src/fcntl.rs:28:1
   |
28 | / libc_bitflags! {
29 | |     pub struct AtFlags: c_int {
30 | |         AT_REMOVEDIR;
31 | |         AT_SYMLINK_FOLLOW;
...  |
39 | |     }
40 | | }
   | |_^ in this macro invocation
   |
```

The supported Cargo version is not changed by this PR. cargo-hack will continue to work with Cargo 1.26 and above.

> cargo-hack is usually runnable with Cargo versions older than the Rust version
> required for installation (e.g., `cargo +1.31 hack check`). Currently, to run
> cargo-hack requires Cargo 1.26+.

### CODE REVIEW

**Comment by taiki-e** [comment]
bors retry
